// Arithmetic operators
console.log("Arthimetic Operators");
let a = 2, b = 3;
console.log("a+b: ",a+b);
console.log("a-b: ",a-b);
console.log("a*b: ",a*b);
console.log("a/b: ",a/b);
console.log("a%b: ",a%b);//modulus
console.log("a**b: ",a**b);//Exponential
console.log("a++b: ",a++);//post increment
console.log("++a: ",++a);//pre-increment
console.log("a--: ",a--);//post-decrement
console.log("--a: ",--a);//pre-decrement
