//Comparsion operators

console.log("Comparsion operators");
let x=2, y="2";
console.log("x==y: ",x==y);// Loose equality
console.log("x===y: ",x===y);// strict equality
console.log("x!=y: ",x!=y);// Loose inequality
console.log("x!=-y: ",x!==y);// strict inequality
console.log("x>3: ",x>3);
console.log("x<3: ",x<3);
console.log("x>3: ",x<3);
console.log("x>=3: ",x>=3);
console.log("x<=3: ",x<=3);

